### ISSUE TITLE
Wrong calculation on specific value

### ISSUE THREAD

**Issue by ale-rinaldi** [ChizhovVadim/xirr#1]
I'm having an issue on this specific test case:

```golang
		{
			Payments: []Payment{
				Payment{mustParseDate("2022-08-26"), -20},
				Payment{mustParseDate("2022-09-26"), 0.12},
				Payment{mustParseDate("2022-10-26"), 0.12},
				Payment{mustParseDate("2022-11-28"), 0.12},
				Payment{mustParseDate("2022-12-26"), 0.12},
				Payment{mustParseDate("2023-01-26"), 20.12},
			},
			Xirr: 1.074,
		},
```

The calculation returns 1.133 instead of the expected 1.074, that is the correct one.

Increasing the `maxRate` by a 10 factor (from `1000000` to `10000000`) seems to solve the issue.

**Comment by ChizhovVadim** [comment]
Thank you very much for the issue!
I found actual reason wrong computation and fix it myself.

**Comment by ale-rinaldi** [comment]
Even better, mine was just a try-and-hope approach :)

Thanks!
